datatables = {
	people : {
	firstnames : ['Adric', 'Aldo', 'Amison', 'Andrel', 'Arcy', 'Arden', 'Arilyn', 'Arquo', 'Arvus', 'Ashlyn', 'Branon', 'Brace', 'Brance', 'Brena', 'Bricks', 'Candra', 'Canter', 'Carissa', 'Carro', 'Casslyn', 'Cavelle', ' Clave', 'Corille', 'Cross', 'Crowl', 'Cyrene', 'Daphnia', 'Drav', 'Edlun', 'Emeline', 'Grell', 'Helles', 'Hix', 'Holtz', 'Kamelin', 'Kelyr', 'Kobb', 'Kristov', 'Laudius', 'Lauria', 'Lenia', 'Lizete', 'Lorette', 'Lucella', 'Lynthia', 'Mara', 'Milos', 'Morlan', 'Myre', 'Narcus', 'Naria', 'Noggs', 'Odrienne', 'Orlan', 'Phin', 'Polonia', 'Quess', 'Remira', 'Ring', 'Roethe', 'Sesereth', 'Sethla', 'Skannon', 'Stavrul', 'Stev', 'Syra', 'Talitha', 'Tesslyn', 'Thena', 'Timoth', 'Tocker', 'Una', 'Vaurin', 'Veleris', 'Veretta', 'Vestine', 'Vey', 'Volette', 'Vond', 'Weaver', 'Wester', 'Zamira', 'Zara'],
	lastnames : ['Arran', 'Athanoch', 'Basran', 'Boden', 'Booker. Ankhayat', 'Bowman', 'Breakiron', 'Brogan', 'Clelland', 'Clermont', 'Coleburn', 'Comber', 'Daava', 'Dalmore', 'Danfield', 'Dunvil', 'Edrad', 'Farros', 'Grine', 'Haig', 'Helker', 'Helles', 'Hellyers', 'Jayan', 'Jeduin', 'Kardera', 'Karstas', 'Keel', 'Kessarin', 'Kinclaith', 'Lomond', 'Maroden', 'Michter', 'Morriston', 'Penderyn', 'Prichard', 'Rowan', 'Salkara', 'Sevoy', 'Skelkallan', 'Slane', 'Strangford', 'Strathmill', 'Templeton', 'Tyrconnell', 'Vale', 'Vedat', 'Walund'],
	nicknames : ['Bell', 'Birch', 'Bird', 'Bliss', 'Bricks', 'Bug', 'Chime', 'Coil', 'Cricket', 'Cross', 'Crow', 'Echo', 'Flint', 'Frog', 'Frost', 'Grip', 'Hook', 'Ink', 'Junker', 'Mist', 'Moon', 'Nail', 'Needle', 'Ogre', 'Pool', 'Ring', 'Ruby', 'Silver', 'Skinner', 'Song', 'Spur', 'Tackle', 'Thistle', 'Thorn', 'Tick Tock', 'Trick', 'Vixen', 'Whip', 'Wicker'],
	gender : [['man','he'],['man','he'],['woman','she'],['woman','she'],['person','they']],
	heritage: ['Skovlander','Skovlander','Iruvian','Dagger Islander','Severosi','Tycherosi'],
	looks : ['large','lovely','weathered','chisled','handsome','athletic','slim','dark','fair','stout','delicate','scarred','bony','worn','rough','plump','wiry','striking','short','tall','sexy','wild','elegant','stooped','cute','plain','old','young','stylish','strange','disfigured','maimed','crippled','tattooed','with glasses','with a monocle','with a prothetic','with long hair','with a beard','with a wig','with a bald head'],
	goals: ['gain wealth','gain power','gain authority','gain prestige','gain fame','gain control','acquire knowledge','seek pleasure','enact revenge','gain freedom','gain personal acheivement','gain happiness','gain infamy','gain the fear of others','gain respect','experience love','affect change','spread chaos','spread destruction','meter out justice','cooperate'],
	methods : ['violence','threats','negotiation','study','manipulation','strategy','theft','arcane','commerce','hard work','law','politics','sabotage','subterfuge','alchemy','blackmail','teamwork','espionage', 'chaos'],
	professions : {
		common: ['Baker', 'Barber', 'Blacksmith', 'Brewer', 'Butcher', 'Carpenter', 'Cartwright', 'Chandler', 'Clerk', 'Cobbler', 'Cooper', 'Cultivator', 'Driver', 'Dyer', 'Embroiderer', 'Fishmonger', 'Gondolier', 'Guard', 'Leatherworker', 'Mason', 'Merchant', 'Roofer', 'Ropemaker', 'Rug Maker', 'Servant', 'Shipwright', 'Criminal', 'Tailor', 'Tanner', 'Tinker', 'Vendor', 'Weaver', 'Woodworker', 'Goat Herd', 'Messenger', 'Sailor'],
		rare : ['Advocate', 'Architect', 'Artist', 'Author', 'Bailiff', 'Apiarist', 'Banker', 'Bounty', 'Hunter', 'Clock Maker', 'Courtesan', 'Furrier', 'Glass Blower', 'Diplomat', 'Jailer', 'Jeweler', 'Leech', 'Locksmith', 'Magistrate', 'Musician', 'Physicker', 'Plumber', 'Printer', 'Scholar', 'Scribe', 'Sparkwright', 'Tax Collector', 'Treasurer', 'Whisper', 'Composer', 'Steward', 'Captain', 'Spirit Warden', 'Journalist', 'Explorer', 'Rail Jack', 'Soldier']
	},
	clothes : ['using crutches', 'using acane', 'using wheelchair','a Tricorn Hat', 'a Long Coat', 'a Hood & Veil', 'a Short Cloak', 'a Knit Cap', 'a Slim Jacket', 'a Hooded Coat', 'a Tall Boots', 'Work Boots', 'a Mask & Robes', 'a Suit & Vest', 'a Collared Shirt', 'Suspenders', 'a Rough Tunic', 'a Skirt & Blouse', 'a Wide Belt', 'a Fitted Dress', 'a Heavy Cloak', ' Thick Greatcoat', 'Soft Boots', 'Loose Silks', 'Sharp Trousers', 'a Waxed Coat', 'a Long Scarf', 'Leathers', 'an Eelskin Bodysuit', 'Hide & Furs', 'a Uniform', 'Tatters', 'Fitted Leggings', 'an Apron', 'Heavy Gloves', 'a Face Mask', 'a Tool Belt'],
	traits: ['charming', 'cold', 'cavalier', 'brash', 'suspicious', 'obsessive', 'shrewd', 'quiet', 'moody', 'fierce', 'careless', 'secretive', 'ruthless', 'calculating', 'defiant', 'gracious', 'insightful', 'dishonest', 'patient', 'vicious', 'sophisticated', 'paranoid', 'enthusiastic', 'elitist', 'savage', 'cooperative', 'arrogant', 'confident', 'vain', 'daring', 'volatile', 'candid', 'subtle', 'melancholy', 'enigmatic', 'calm'],
	interests: ['fine whiskey, wine and beer', 'fine food and restaurants', 'fine clothes, jewelry and furs', 'fine arts, opera and theater', 'painting, drawing and sculpture', 'history and legends', 'architecture and furnishings', 'poetry, novels and writing', 'pit-fighting and duels', 'forgotten gods', 'Ecstacy of the Flesh', 'Path of Echos', 'Weeping Lady and charity', 'antiques, artifacts and curios', 'horses and riding', 'gadgets and new technology', 'collecting weapons', 'music, instruments and dance', 'hunting and shooting', 'cooking and gardening', 'gambling, cards and dice', 'natural philosophy', 'drugs, essences and tobacco', 'lovers, romance and trysts', 'parties and social events', 'exploration and adventure', 'pets', 'crafting', 'ships and boating', 'politics and journalism', 'arcane books and rituals', 'spectrology and electroplasm', 'alchemy and medicine', 'essences and alchemy', 'demon lore and legends', 'pre-cataclysm legends'],
	quirks: ['Superstitious. Believes in signs, magic numbers','Devoted to their family','Married into important / powerful family','Holds their position to spy for another faction','Reclusive. Prefers to interact via messengers','Massive debts (to banks / criminals / family)','Blind to flaws in friends, allies, family, etc','Once hollowed, then restored. Immune to spirits','Has chronic illness which requires frequent care','Secretly (openly?) controlled by possessing spirit','Serves a demon\'s agenda (knowingly or not)','Proud of heritage, traditions, native language','Concerned with appearances, gossip, peers','Drug/alcohol abuser. Often impaired by their vice','Holds their position due to blackmail','Relies on council to make decisions','Involved with war crimes from the Unity War','Leads a double life using cover identity','Black sheep / outcast from family or organization','In prison or under noble\'s house arrest','Well-traveled. Connections outside Doskvol','Revolutionary. Plots against the Imperium','Inherited their position. May not deserve or want it','Minor celebrity. Popularized in print / song / theater','Scandalous reputation (deserved or not)','Surrounded by sycophants, supplicants, toadies','Spotless reputation. Highly regarded','Bigoted against culture / belief / social class','Visionary. Holds radical views for future','Cursed, haunted, harassed by spirits or demon','Intense, unreasonable phobia or loathing','Extensive education on every scholarly subject','Keeps detailed journals, notes, records, ledgers','Is blindly faithful to an ideal, group, or tradition','Deeply traditional. Opposed to new ideas, methods','A fraud. Some important aspect is fabricated'],
	deviltraits: {
		eyes: ['cat\'s','black','glowing','red','yellow','purple','segmented','snake\'s','oversized','bug','shark\'s'],
		claws: ['retractable','razor sharp','bear','long','raptor','cat','crab','lobster'],
		hair: ['feather','vine','floating','snakes for','moving'],
		skin: ['fish scale','shark','snake','sticky','tumorous','hairless','spikey','fur covered','slick','slimy'],
		horns: ['goat','ram','bull','long','filed dull','twisting','sharp'],
		teeth: ['shark','sharp','no','vampire','wolf','manibles instead of']
	}
	},
	streets : {
		mood: ['A dark','A cold','A bright','A lively','A quiet','A refined','An abandoned','A decrepit','A cramped','A noisy','A cozy','A warm'],
		sights: ['rain slick','oil slick','dancing shadows','flickering lights','mist','fog','frost','fleeting shapes','echoes in the ghost field','soot','ash clouds','grime','crackling electricity','wires','mechanisms'],
		sounds: ['machinery','workers','fluttering cloth','howling wind','laughter','song','music','whispers','echoes','strange voices','thunder','driving rain','bells','clock chimes','harbor horns'],
		smells: ['cooking fires','furnaces','damp wood','decay','refuse','animals','hides','blood','chemicals','distillates','fumes','rain water','the ocean','ozone','electroplasmic discharges'],
		use: ['residential housing','residential housing','residential housing','crafts','crafts','crafts','labor','labor','labor','shops','shops','shops','trade','trade','trade','hospitality','hospitality','hospitality','law and government','law and government','public space','public space','power','power','manufacturing','manufacturing','transportation','transportation','leisure','leisure','vice','entertainment','storage','cultivation','academia','artists'],
		type: ['narrow lane','narrow lane','narrow lane','tight alley','tight alley','tight alley','twisting street','twisting street','twisting street','rough road','rough road','rough road','bridge','bridge','bridge','waterway','waterway','waterway','closed court','closed court','open plaza','open plaza','paved avenue','paved avenue','tunnel','tunnel','wide boulevard','wide boulevard','roundabout','roundabout','elevated road','flooded street','suspended lane','suberanean path','floating barge','gated lane'],
		details: ['metal supports','ironwork gates','fences','belching chimneys','metal grates, hatches and doors','clockwork mechanisms','rigging and cables','stairs and ramps','terraces','wooden scaffolds','skyways','rooftop spaces','rails and traincars','hidden passages','banners and pendants','festival decorations','crowds','rioters','parade goers','street performers','makeshift stalls','crisscrossing routes','gang markings','patrol posts','lookouts','stockades','street criers','news stands','public notices','stray animals','landscaping','muck and mire','construction','foul runoff and fumes','orphans','beggars','ancient ruins','leering gargoyles','spirit wards','eerie emptiness','quarantine signs','shrines and offerings'],
		props: ['Nets','Ropes','Crates','Boxes','Chains','Cables','Drain Pipes', 'Water Pump', 'Oil Drums', 'Brick Pile', 'Iron Bars', 'Wooden Boards', 'Cut Stones', 'Loose Rocks', 'Cement Buckets', 'Sewer Grate', 'Rotting Refuse', 'Mud Puddles', 'Discarded Junk', 'Carrion & Crows', 'Sodden Trash', 'Carriages', 'Push Carts', 'Moored Boats', 'Cargo Barge', 'Gondolas', 'Wagons', 'Crane & Pulleys', 'Cargo Bales', 'Metal Ingots', 'Industrial Forge', 'Coal / Fuel', 'Waste Bins', 'Street Lamps', 'Electric Wires', 'Junction Boxes', 'Spotlight Tower', 'Clock Tower', 'Messenger Post', 'Withered Trees', 'Monument', 'Fountain', 'Mossy Ruin', 'Collapsed Bldg.', 'Flimsy Hovel', 'Barricade', 'Gate', 'Checkpoint', 'Piled Rubble', 'Canal Lock', 'Lightning Barrier', 'Food Stall', 'Vendor Stall', 'Barrels, Casks', 'Makeshift Shrine', 'News Stand', 'Stockade'],
		names: ['Black Hill','Mill','Porter','Market','Main','Prichard','Vale','Keel','Park','Bowmore','Silver','Gold','Barrow','Unity','Silvermark','Goldcrest','Ruby','Saphire','Strangford','Wott','Canal','Hill','Clerk','Charter','Jayan','Drake','Pendery','Dalmore','Imperial','Rail','Coal','Iron','Brick','Dunvil','Black Rock','Wright','Crane','Forge','Crow','Sash','Strathmill','Bucket','Ash','Cinder','Rye','Candle','Hulliver','Ink','Dock','North Hook','Carter','Plume','Saltford','Song','Paper','Bell','String','Spark','Fogcrest','Ankhayat','Greenwater','Highwater','Chimewater','Sweetwater','Ringwater','Rowan','Mistshore','Scurlock','Comber','Coleburn','Flint','Whitecrown','Swancrest']
	},
	buildings: {
		exteriorMaterial: ['Gray Brick', 'Stone & Timbers','Cut Stone Blocks','Wooden Boards','Plaster Board & Timbers','Metal Sheeting'],
		exteriorDetails: ['Tile Work', 'Iron Work', 'Glass Work', 'Stone Work', 'Wood Work', 'Landscaping'],
		commonUse: ['bunk house', 'inn', 'tavern', 'gambling hall', 'drug den', 'brothel', 'market', 'workshop', 'bakery', 'butchery', 'forge', 'tailory', 'work house', 'goat stables', 'brewery', 'watch post', 'court', 'jail', 'dock', 'ruin', 'row houses', 'tenements', 'apartment building', 'small house', 'bath house', 'shrine', 'tattoist', 'physicker', 'fighting pits', 'square with fountain', 'grotto', 'warehouse', 'stockyard', 'factory', 'refinery', 'eelery', 'mushroom garden'],
		rareUse: ['market house', 'restaurant', 'bar', 'lounge', 'academy', 'salon', 'cafe', 'floristry', 'tabacconist', 'book shop', 'jeweler', 'clothier', 'gallery', 'apothecary', 'horse stable', 'distillery', 'vintner', 'master artisan', 'boat house', 'theater', 'opera house', 'apartment building', 'town house', 'manor house', 'villa', 'clinic', 'temple', 'cistern', 'watch post', 'park', 'monument', 'archive', 'spiritualist', 'bank', 'alchemist', 'power plant', 'radiant energy garden'],
		secondaryArea: ['on the second floor','in the basement','in a cellar','in a secondary partition','from a separate entrance','in a back room'],
		details: ['dripping water', 'creaking floorboards', 'roaring fires', 'smoky lamps', 'buzzing electric lights', 'ticking clockworks', 'plants and flowers', 'wall hangings and artwork', 'shattered windows', 'heavy curtains and thick carpets', 'dust and deritus', 'wear and damage', 'theadbare and tattered furnishings', 'utilitarian furnishings', 'elegant finery', 'lush and comfortable furnishings', 'rough spun simplicity', 'spartan austerity', 'circular stairs and ladders', 'secret doors', 'catwalks', 'skylights', 'a balcony', 'a cellar', 'strange devices', 'weird artifacts', 'spirit wards and old runes', 'piled jumbles of curios', 'antique appointments', 'shrines and altars','drafty and cold', 'stout and quiet', 'cozy and warm', 'vaulted and spacious', 'low and cramped', 'rickety and ramshackled'],
		items: ['Chalkboard', 'Desks', 'Papers', 'Maps', 'Charts', 'Diagrams', 'Books', 'Scrolls', 'Bookcases', 'Lamp', 'Inkwell', 'Writing Desk', 'Clock', 'Cabinet', 'Shelves', 'Table', 'Chairs', 'Notebooks', 'Bed', 'Bureau', 'Vanity', 'Bunks', 'Stools', 'Trunks', 'Basin', 'Pitcher', 'Mirror', 'Sofa', 'Divan', 'Music Box', 'Couches', 'Table', 'Lamps', 'Drapery', 'Pillows', 'Cushions', 'Counter', 'Sink', 'Cabinets', 'Cookfire', 'Pots', 'Pans', 'Utensils', 'Dining Table', 'Chairs', 'Cutlery', 'Game Board', 'Cards', 'Dice', 'Larder', 'Spices', 'Meat Hooks', 'Wine', 'Beer', 'Whiskey', 'Pedestal', 'Statue', 'Paintings', 'Bird Cage', 'Quill', 'Diary', 'Bell', 'Book', 'Candle', 'Fireplace', 'Rug', 'Armchair', 'Curtains', 'Vases', 'Flowers', 'Instruments', 'Music Sheets', 'Exam Chair', 'Medical Tools', 'Burner', 'Vials', 'Beakers', 'Workbench', 'Tools', 'Rags', 'Weapons', 'Ammunition']
	},
	scores: {
		contact: ['a friend of a PC', 'the rival of a PC', 'the vice purveyor of a PC','a contact of the crew','a ghost, demon or forgotten god'],
		work: ['stalk', 'surveil', 'sabotage', 'perform arson against','lift from','plant something on','poison','arrange an accident for', 'burgle from', 'plan a heist against', 'impersonate', 'misdirect', 'assassinate', 'dissapear', 'kidnap and ransom', 'terrorize', 'extort', 'destroy objects belonging to', 'deface property belonging to', 'raid the home of', 'defend the home of', 'rob from', 'strong-arm', 'escort', 'secure', 'smuggle', 'deliver something to', 'blackmail', 'discredit', 'con', 'spy on', 'locate', 'hide', 'negotiate with', 'threaten', 'curse', 'sanctify', 'banish', 'summon', 'extract essence from', 'place runes on something owned by', 'remove runes from something owned by', 'perform a ritual with', 'stop a ritual by', 'hollow', 'revivify'],
		connections: ['an academic', 'a scholar', 'a laborer', 'a tradesman', 'a courier', 'a sailor', 'a merchant', 'a shopkeeper', 'an artist', 'a writer', 'a doctor', 'an alchemist', 'a drug dealer', 'a drug supplier', 'a mercenary', 'a thug', 'a fence', 'a gambler', 'a spy', 'an informant', 'a smuggler', 'a theif', 'a crime boss', 'a noble', 'an official', 'a banker', 'a captain', 'a revolutionary', 'a refugee', 'a member of the clergy', 'a cultist', 'a constable', 'an inspector', 'a magistrate', 'a ward boss', 'a ghost of {connection}','an occult collector', 'a vampire', 'an undead being', 'a demon in disguise', 'a possessed human', 'a hollow', 'a whisper', 'a cultist'],
		twist: ['an element is a cover for heretic spirit cult practices','an occultist has foreseen this job and warned the parties involved','rogue spirits possess some/most/all of the people involved','rogue spirits haunt the location','the job furthers a demon\'s secret agenda','the job furthers a vampire\'s secret agenda','an element is a front for a criminal enterprise','a dangerous gang uses the location','the job is a trap laid by their enemies','the job is a test for another job','the job furthers a merchant lord\'s secret agenda','the job furthers a crime boss\'s secret agenda','the job requires travel by electro-rail','they must visit the death-lands to do the job (perhaps to the Lost District, outside the lightning barrier)','the job requires sea travel','the location moves around','the job furthers a revolutionary\'s secret agenda','the job furthers a city official\'s secret agenda'],
		factions: ['The Unseen', 'Lord Scurlock', 'The Circle of Flame', 'The Lampblacks', 'The Dimmer Sisters', 'The Billhooks', 'The Gray Cloaks', 'The Fog Hounds', 'The Council', 'The Foundation', 'The Spirit Wardens', 'The Imperial Military', 'The Sparkwrights', 'A Consulate', 'The Leviathan Hunters', 'The Gondoliers', 'The Cabbies', 'The Ecstacy of the Flesh', 'The Forgotten Gods', 'The Skovlander Refugees', 'The Silver Nails', 'The Hive', 'The Crows', 'The Red Sashes', 'The Grinders', 'The Wraiths', 'Ulf Ironborn', 'The Lost', 'Ironhook Prison', 'The Bluecoats', 'The Inspectors', 'The Ink Rakes', 'The Cyphers', 'The Ministry of Transport', 'The Ministry of Provisions', 'The Sailors', 'The Dockers', 'The Rail Jacks', 'The Brigade', 'The Weeping Lady', 'The Path of Echoes', 'The Reconciled', 'The Deathlands Scavengers']
	}
}
